### ISSUE TITLE
Application does not work properly

### ISSUE THREAD

**Issue by sushilraj786** [MarsiBarsi/angular-library-to-web-components-demo#3]
When I run **npm run build:elements**, I am getting errors.

![err](https://user-images.githubusercontent.com/26320913/68024993-b2d24580-fcd1-11e9-906f-ec498a81de68.png)

Can you please look into it and let us know the root cause and fix.

**Comment by kolkov** [comment]
Remove `''` from path if you on Windows

**Comment by Gordondalos** [comment]
![image](https://user-images.githubusercontent.com/7421933/74511636-9ed4eb80-4f30-11ea-8916-be741975de43.png)
remove single coma on path
